version: '3'

services:
    apache:
        build: .
        ports:
            - 80:80
        restart: always
        volumes:
            - ./.:/var/www/html/
        links:
            - mysql

    mysql:
        image: mysql:5.7.32
        ports:
            - 3306:3306
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: stats

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        restart: always
        ports:
            - 8000:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
