version: "3.1"
services:
    www:
        build: .
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html/
        links:
            - db

    db:
        platform: linux/x86_64
        image: mysql:8.0
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: stats
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./database:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
